# Generated by Django 2.2 on 2019-08-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Generos',
                'db_table': 'genre',
                'ordering': ('desc',),
            },
        ),
    ]
